### ISSUE TITLE
Error on Ubuntu; server closes with 500 on downloading SDL2 tarball. Only present on Linux.

### ISSUE THREAD

**Issue by ProjectHSI** [libsdl-org/setup-sdl#23]
Error on downloading and extracting the SDL2 tarball, of which is only present on Ubuntu.
```
 /home/runner/work/_actions/libsdl-org/setup-sdl/main/packed/index.js:46431
    throw new import_request_error.RequestError(message, 500, {
          ^

RequestError [HttpError]: other side closed
    at /home/runner/work/_actions/libsdl-org/setup-sdl/main/packed/index.js:46431:11 {
  status: 500,
  request: {
    method: 'GET',
    url: 'https://api.github.com/repos/libsdl-org/SDL/zipball/15ead9a40d09a1eb9972215cceac2bf29c9b77f6',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-rest.js/20.0.2 octokit-core.js/5.0.2 Node.js/20.8.1 (linux; x64)',
      authorization: 'token [REDACTED]'
    },
    request: { hook: [Function: bound bound register] }
  }
}
```

**Comment by madebr** [comment]
Have you recently run a lot of (parallel) builds?
I've also seen this error and think this is caused by using up all GitHub tokens.
I opened https://github.com/libsdl-org/setup-sdl/issues/22 to think about caching the SDL sources, and/or fetch the sources in a different way.

**Comment by ProjectHSI** [comment]
> Have you recently run a lot of (parallel) builds? I've also seen this error and think this is caused by using up all GitHub tokens. I opened #22 to think about caching the SDL sources, and/or fetch the sources in a different way.

This is correct. I run 4 builds in parallel. 2 for Linux (gcc & clang), 1 for Windows (cl/msvc), and 1 for MacOS (gcc). The latter two both succeed (at this step).

It could be possible that the github tokens dried out but that wouldn't explain the big picture as Windows and MacOS builds both succeed (they failed due to #24 however, might be my fault).

**Comment by KenVanHoeylandt** [comment]
I have the same issue:
https://github.com/ByteWelder/Tactility/actions/runs/7596080088/job/20689375551?pr=16
This is my first CI job with the SDL dependency.

**Comment by ProjectHSI** [comment]
> I have the same issue: https://github.com/ByteWelder/Tactility/actions/runs/7596080088/job/20689375551?pr=16 This is my first CI job with the SDL dependency.

HI there.
I'll have a look at finding a workaround for Linux. I think you have to clone the version of SDL you want to a directory, tell the CMake script to use Vendored SDL via a variable set by the CI script. As far as I know installing SDL the normal way via a Vendored SDL won't work on MacOS (it just freezes for some reason).

I'll report back when this works.

**Comment by KenVanHoeylandt** [comment]
Thanks! It works for me now:
https://github.com/ByteWelder/Tactility/actions/runs/7603080544/job/20704376936?pr=16

**Comment by madebr** [comment]
Does this still happen?
Before implementing a different way to fetch the SDL sources, I'd like to try reverting the nodejs version from 20 to 16.
You can test this by switching to the [`try-node16` branch](https://github.com/libsdl-org/setup-sdl/tree/try-node16).

**Comment by KenVanHoeylandt** [comment]
The original issue seems to be solved, as the action's data is fetched from cache:

> Looking up a SDL_image build in the cache
>   setup-sdl SDL_image state = e93427b44940a3a7ca50cf2ffb7fdd49fa615dee40b0e8f9e7ea19f0694859f3
>   Cache Size: ~0 MB (261901 B)
>   /usr/bin/tar -xf /home/runner/work/_temp/3c36ccc5-403b-463b-a9d8-c0c99bbbdfd1/cache.tzst -P -C /home/runner/work/Tactility/Tactility --use-compress-program unzstd
>   Cache restored successfully
>   SDL_image found in the cache: key = setup-sdl-SDL_image-e93427b44940a3a7ca50cf2ffb7fdd49fa615dee40b0e8f9e7ea19f0694859f3
> SDL_image version is 2.8.2
> Received 261901 of 261901 (100.0%), 0.2 MBs/sec

I cannot yet conclude whether it is completely fixed because my build now fails with a different reason:

>  [ 80%] Linking C executable app-sim
> /usr/bin/ld: cannot find -lSDL2: No such file or directory

This is possibly an issue in my project, so I need to investigate it.
Context: https://github.com/ByteWelder/Tactility/actions/runs/7603080544/job/20704376936?pr=16

**Comment by madebr** [comment]
@KenVanHoeylandt 
The SDL configuration files generate targets in the SDLxxxx namespace.
This patch fixes that:
```diff
--- a/app-sim/CMakeLists.txt
+++ b/app-sim/CMakeLists.txt
@@ -7,7 +7,7 @@ target_link_libraries(app-sim
     PRIVATE tactility-core
     PRIVATE lvgl
     PRIVATE lv_drivers
-    PRIVATE SDL2
+    PRIVATE SDL2::SDL2
 )
 
 target_link_libraries(app-sim ${SDL2_LIBRARY})
```
Likewise, for SDL_image, link to `SDL2_image::SDL2_image`.

**Comment by ProjectHSI** [comment]
Hey sorry I didn't get your messages, I hope you're still online. I'll investigate the potential fixes.

**Comment by ProjectHSI** [comment]
On the Node 20 branch, this still happens.
Investigating the Node 16 branch.

**Comment by ProjectHSI** [comment]
By changing the branch using
```
- uses: libsdl-org/setup-sdl@try-node16
```
<img width="1608" alt="Screenshot 2024-01-22 070104" src="https://github.com/libsdl-org/setup-sdl/assets/57279339/36212f5a-1378-4a95-8a09-52386b1242c4">

it doesn't work using a different message.

**Comment by KenVanHoeylandt** [comment]
@madebr Thanks, that solved it! I ended up using the proper variable: `${SDL2_LIBRARIES}`

The build then succeeded, but the original problem was back in the build afterwards:
https://github.com/ByteWelder/Tactility/actions/runs/7603931718/job/20706241039

Conclusion: it fails intermittently depending on whether it uses the cached data or not.

**Comment by ProjectHSI** [comment]
@madebr I'm sorry if you're busy working on SDL2 or this project but this issue isn't fixed yet - Nothing has changed on the master branch.

**Comment by ProjectHSI** [comment]
> I'll have a look at finding a workaround for Linux. I think you have to clone the version of SDL you want to a directory, tell the CMake script to use Vendored SDL via a variable set by the CI script. As far as I know installing SDL the normal way via a Vendored SDL won't work on MacOS (it just freezes for some reason).

Try doing this.

**Comment by Alloyed** [comment]
still occurring: https://github.com/Alloyed/KitsBlips/actions/runs/15185451044/job/42704680564

```
/home/runner/work/_actions/libsdl-org/setup-sdl/main/packed/index.js:82893
    const requestError = new RequestError(message, 500, {
                         ^

RequestError [HttpError]: other side closed
    at fetchWrapper (/home/runner/work/_actions/libsdl-org/setup-sdl/main/packed/index.js:82893:26) {
  status: 500,
  request: {
    method: 'GET',
    url: 'https://api.github.com/repos/libsdl-org/SDL/zipball/8d604353a53853fa56d1bdce0363535605ca868f',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-rest.js/21.1.1 octokit-core.js/6.1.5 Node.js/20.19.1 (linux; x64)',
      authorization: 'token [REDACTED]'
    },
    request: {
      hook: [Function: bound bound register],
      parseSuccessResponseBody: false
    }
  },
  response: undefined,
  cause: TypeError: fetch failed
      at node:internal/deps/undici/undici:13510:13
      at async fetchWrapper (/home/runner/work/_actions/libsdl-org/setup-sdl/main/packed/index.js:82867:21) {
    [cause]: SocketError: other side closed
        at TLSSocket.onSocketEnd (/home/runner/work/_actions/libsdl-org/setup-sdl/main/packed/index.js:52754:22)
        at TLSSocket.emit (node:events:536:35)
        at endReadableNT (node:internal/streams/readable:1698:12)
        at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
      code: 'UND_ERR_SOCKET',
      socket: {
        localAddress: '10.1.0.86',
        localPort: 40456,
        remoteAddress: '140.82.114.6',
        remotePort: 443,
        remoteFamily: 'IPv4',
        timeout: undefined,
        bytesWritten: 1152,
        bytesRead: 4135
      }
    }
  }
}
```

relevant part of actions config: ```
    strategy:
      fail-fast: false # show all errors for each platform (vs. cancel jobs on error)
      matrix:
        include:
          - name: Linux
            os: ubuntu-24.04
          - name: macOS
            os: macos-14
            # https://github.com/libsdl-org/setup-sdl/issues/33
            # extra-flags: -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64"
          - name: Windows
            # https://github.com/actions/runner-images/issues/10980
            os: windows-2025

    steps:
      - uses: libsdl-org/setup-sdl@main
        id: sdl
        with:
          install-linux-dependencies: true
          version: 3-latest
          version-sdl-image: 3-latest
```

**Comment by HexDecimal** [comment]
`try-node16` worked to setup SDL2 but I needed a later revision to setup SDL3 or else I'd run into issue #26. Rebasing `try-node16` onto `main` has the same `status: 500` error as before so I suspect `try-node16` doesn't actually have any effect.

I did a bisect between `try-node16` and `main`. From my primitive testing, the regression was caused by 14da8bf7744e4edd0af9d2b9e1b1e6de1289aed0, so I'll use the revision directly before that:

```yml
- uses: libsdl-org/setup-sdl@6574e20ac65ce362cd12f9c26b3a5e4d3cd31dee
```

This lets me setup SDL3 on GitHub's Ubuntu runners for now.

Interestingly enough 14da8bf7744e4edd0af9d2b9e1b1e6de1289aed0 was made after this issue was initially posted. So apparently this issue was resolved for a moment before regressing later on?

**Comment by madebr** [comment]
Can you please try current main? I pushed a patch yesterday that should work around an issue  when using `install-linux-dependencies: true`.

**Comment by HexDecimal** [comment]
I can conform the current main revision `libsdl-org/setup-sdl@1894460666e4fe0c6603ea0cce5733f1cca56ba1` is working so far.

Previous versions and workarounds had random failures, so I'll report back here if that happens again.
